export const PROJECTS = [
  {
    id: "project-1",
    title: "Party Animal Music Video ",
    description: "A music video my classmates and I worked on. I created the mixed animation for this video and helped with cinematography.",
    thumbnail: "https://img.youtube.com/vi/wI0UjiOcLnM/hqdefault.jpg",
    videoUrl: "https://youtu.be/wI0UjiOcLnM?si=Ah3s6Slz4QbHCnxJ",
  },
  {
    id: "project-2",
    title: "Warhammer Hype Video",
    description: "A hype video I made on my friend and his Warhammer collection. I planned, filmed, and edited this. I also utilized the VU screen to help create these shots.",
    thumbnail: "https://img.youtube.com/vi/rsaBrMKowHQ/hqdefault.jpg",
    videoUrl: "https://youtu.be/rsaBrMKowHQ?si=3eSqGCC_pUq9bJzZ",
  },
  {
    id: "project-3",
    title: "A very cool car mechanic named Keyner",
    description: "A documentary I created that follows Keyner Botello, a car repair shop owner, and his employees. I filmed and edited this project.",
    thumbnail: "https://img.youtube.com/vi/Qbytbp1JK-c/hqdefault.jpg",
    videoUrl: "https://www.youtube.com/watch?v=WZ64MJcWt-k",
  },
  {
    id: "project-4",
    title: "Cold Open ",
    description: "A quick package I edited for our 6pm newscast. I do these packages weekly.",
    thumbnail: "https://img.youtube.com/vi/xnogUpon2PY/hqdefault.jpg",
    videoUrl: "https://youtu.be/xnogUpon2PY",
  },
  {
    id: "project-5",
    title: "Tampa Hoy Edit",
    description: "A package I edited for our Spanish newscast Tampa Hoy. ",
    thumbnail: "https://img.youtube.com/vi/T35SASRyowg/hqdefault.jpg",
    videoUrl: "https://www.youtube.com/watch?v=T35SASRyowg",
  },
  {
    id: "project-6",
    title: "Tampa Skyline Drone Footage ",
    description: "My first time filming with a drone and editing the footage",
    thumbnail: "https://img.youtube.com/vi/B0ion4gP4hw/hqdefault.jpg",
    videoUrl: "https://youtube.com/shorts/B0ion4gP4hw?si=TXXMmTUlejnqGqsd",
    openInNewTab: true,
  }
];
// export const GALLERY = [
//   { id: 1, url: "/photo_gallery/tall1.jpg", size: "tall" },
//   { id: 2, url: "/photo_gallery/wide1.jpg", size: "wide" },
//   { id: 3, url: "/photo_gallery/flowers.JPG", size: "small" },
//   { id: 4, url: "/photo_gallery/DSC_6640.jpg", size: "small" },
//   { id: 5, url: "/photo_gallery/wide2.jpg", size: "wide" },
//   { id: 6, url: "/photo_gallery/tall2.jpg", size: "tall" },
//   { id: 7, url: "/photo_gallery/swan1.jpg", size: "small" },
//   { id: 8, url: "/photo_gallery/DSC_4657.jpg", size: "small" },
//   { id: 9, url: "/photo_gallery/wide3.jpg", size: "wide" },
//   { id: 10, url: "/photo_gallery/tall3.jpg", size: "tall" },
//   { id: 11, url: "/photo_gallery/DSC05874.jpg", size: "small" },
//   { id: 12, url: "/photo_gallery/DSC05981.jpg", size: "small" },
//   { id: 13, url: "/photo_gallery/DSC_4647.jpg", size: "small" },
//   { id: 14, url: "/photo_gallery/swan2.jpg", size: "small" },
//   { id: 15, url: "/photo_gallery/DSC_4545.jpg", size: "small" },
// ];

export const GALLERY = [
  { id: 1, url: "/photo_gallery/tall1.jpg" },
  { id: 2, url: "/photo_gallery/wide1.jpg" },
  { id: 3, url: "/photo_gallery/swan2.jpg"},
  { id: 4, url: "/photo_gallery/DSC_6550.jpg" },
  // { id: 5, url: "/photo_gallery/wide2.jpg" },
  { id: 6, url: "/photo_gallery/DSC05981.jpg" },
  { id: 7, url: "/photo_gallery/swan1.jpg" },
  { id: 8, url: "/photo_gallery/DSC05874.jpg" },
  { id: 9, url: "/photo_gallery/wide3.jpg" },
  { id: 10, url: "/photo_gallery/tall3.jpg"},
  { id: 11, url: "/photo_gallery/DSC_4657.jpg"},
  { id: 12, url: "/photo_gallery/tall2.jpg" },
  { id: 13, url: "/photo_gallery/DSC_4647.jpg" },
  { id: 14, url: "/photo_gallery/flowers.jpg" },
  { id: 15, url: "/photo_gallery/DSC_4545.jpg" },
  // { id: 16, url: "/photo_gallery/DSC_6640.jpg" },
  {id : 17, url: "/photo_gallery/wide2.jpg"},
];